Develop  to master
ibrolive/Design-Teardown pull request #1
Opened 2019-05-27 17:54 UTC by Dongmo12

2019-05-27 18:13 UTC, JamesOkunlade commented on css/style.css
> +    /* margin-right: -150px; */
Remove this line.

2019-05-27 18:14 UTC, JamesOkunlade commented on css/style.css
> +    /* background-color: black; */
Remove this line too. Don't leave unused styles in your code as comments.

2019-05-27 18:14 UTC, JamesOkunlade requested changes
### Hello guys!!, 

Great work on the design teardown project. 

There are some avoidable errors in your HTML code. Parse your code through the [w3C markup validator](https://validator.w3.org/) to identify and fix these errors. 

Also, the commits are too unevenly distributed for a collaborative project. Ensure to switch more often in your future collaborative projects. 

Fix the HTML errors and request another code review. Add me as the TSE so I can follow up.

Happy coding!

2019-05-27 21:58 UTC, ibrolive commented
Hi @JamesOkunlade. Thanks for your feedback and for taking the time to review this. HTML errors have been fixed.

2019-05-28 20:45 UTC, JamesOkunlade approved these changes
### **Well did guys!!!**

You're good to go. Merge to master, close pull request and fill the project completion form.

Good luck with your future projects.:+1:+1:

2019-05-29 07:09 UTC, merged